### ISSUE TITLE
Travis deploy stage doesn't set Gradle to executable

### ISSUE THREAD

**Issue by TheGlitch76** [liachmodded/carttemplate#1]
Deploy's `install` is set to run the command `true` (which does nothing) instead of `chmod +x gradlew`, causing that build to always fail.

**Comment by liach** [comment]
Ah, it actually is a bug from github that it fails to carry the executable information from the template git repository to the copied git repo. You need to go to your newly created repo for now and run `git update-index --chmod +x gradlew` for now.

**Comment by liach** [comment]
Oh, github apparently has fixed this
